### PR TITLE
feat(api-v2): Generate IIIF manifest (DSP-50)

### PR DESCRIPTION
**Pull request by benjamingeer**
resolves DSP-50

### CODE REVIEW

**Review by SepidehAlassi — CHANGES_REQUESTED** [review]
Can you please add a test for the structure of the returned manifest?

**Comment by benjamingeer** [comment]
@SepidehAlassi Is this OK now?

**Review by SepidehAlassi — APPROVED** [review]
This is great, thanks for all your work.

**Comment by benjamingeer** [comment]
Thanks for reviewing!

**Pull request merged**
