### PR TITLE
feat!: Remove isSequenceOf and instead add Segment to DSP-API (DEV-3326)

### PR DESCRIPTION
**Pull request by BalduinLandolt**
### Task Description/Number

Issue Number: DEV-3326

This PR:

- Breaking: Removes `isSequenceOf` and `hasSequenceBounds` from the `knora-base` ontology
- Adds `Segment` etc. as a replacement of sequences

The following will be done in follow-up PRs:

- Add documentation on the new feature
- Add to the persisted test data (so we have examples in `make init-db-test`)
- write non-E2E tests

### PR Type

- [ ] build/chore: maintenance tasks (no production code change)
- [ ] docs: documentation changes (no production code change)
- [x] feat: represents new features
- [ ] fix: represents bug fixes
- [ ] perf: performance improvements
- [ ] refactor: represents production code refactoring
- [ ] test: adding or refactoring tests (no production code change)

### Basic requirements for bug fixes and features

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [x] Yes

### Does this PR change client-test-data?

- [ ] Yes

### CODE REVIEW

**Comment by seakayone** [comment]
As discussed: 

I understand that the removed properties of the ontology are not used in any of our projects and it is therefore safe to delete them from the ontology.

Nonetheless, I would appreciate if we are handling breaking changes in a more not-so-surprising way for our users. Until we have a process for handling this I am indifferent on whether or not we should remove them in this PR. Now I will shutup and write a proposal on a proper depreciation procedure for implementing breaking changes.

**Review by seakayone — APPROVED** [review]

**Review by siers — APPROVED** [review]

**Review by mpro7 — APPROVED** [review]
I didn't find anything suspicious. Should this PR bump the major api version?

**Comment by BalduinLandolt** [comment]
> I didn't find anything suspicious. Should this PR bump the major api version?

Yes, that was the idea (because removing the sequence thing is a breaking change), I guess the exclamation mark should do the trick, right?

**Comment by mpro7** [comment]
> > I didn't find anything suspicious. Should this PR bump the major api version?
> 
> Yes, that was the idea (because removing the sequence thing is a breaking change), I guess the exclamation mark should do the trick, right?

Indeed. I think there were some braking changes in between last major version update and now which didn't bump the number, therefor I needed to ask. Actually we should maybe analyze this maybe on the BE meeting.

**Pull request merged**
