### PR TITLE
DSP-1099 Update Bazel maven rules to see if it fixes problems with macOS Big Sur

### PR DESCRIPTION
**Pull request by subotic**
resolves DSP-1099

### CODE REVIEW

**Comment by subotic** [comment]
As it turns out, the problem we experienced wasn't with Bazel, but the Cisco packet filter which was automatically activated in Big Sur. Removing the packet filters, solved the issue.

**Review by benjamingeer — CHANGES_REQUESTED** [review]
> Removing the packet filters, solved the issue.

Can you document what we need to do, so others don't get the same problem?

**Comment by subotic** [comment]
This is a local macOS Big Sur network issue. Where would you like me to document it? I wrote it inside the YouTrack issues and mentioned it here.

**Comment by benjamingeer** [comment]
If I understand correctly, every developer who uses macOS will need to do some additional configuration to avoid this problem. So a good place to document it would be somewhere under "Development":

https://docs.knora.org/05-internals/development/

**Comment by subotic** [comment]
I've added a note about macOS Big Sur to the Maven dependencies docs.

**Review by benjamingeer — APPROVED** [review]
OK great, thanks!

**Comment by subotic** [comment]
Thanks for the review :-)

**Pull request merged**
