### PR TITLE
fix: key frame extraction (DEV-1513)

### PR DESCRIPTION
**Pull request by seakayone**
Issue Number: DEV-1513

### Basic Requirements

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### PR Type

What kind of change does this PR introduce?

- [x] Bugfix: represents bug fixes
- [ ] Refactor: represents production code refactoring
- [ ] Feature: represents a new feature
- [ ] Documentation: documentation changes (no production code change)
- [ ] Chore: maintenance tasks (no production code change)
- [ ] Style: styles updates (no production code change)
- [ ] Test: all about tests: adding, refactoring tests (no production code change)
- [ ] Other... Please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Does this PR change client-test-data?

- [ ] Yes (don't forget to update the JS-LIB team about the change)
- [x] No

### Other information
This PR contains fixes which prevent the key frame extraction and matrix file creation of the two files:
https://github.com/dasch-swiss/4124-xmlperformance-testdata/blob/main/bitstreams/0.1.mp4
https://github.com/dasch-swiss/4124-xmlperformance-testdata/blob/main/bitstreams/100.mp4

Both files suffer from two different bugs:

1. Fixes processing of very short moving images (0.1.mp4)
The file is too short for any frame to be extracted with the previous implementation which assumed at least five keyframes to be extracted. Change the script to start extracting keyframes at time unit 0, i.e. the beginning of the file and use the first extract frame as the start of the matrix instead of a later possibly non existing one.

2. Fix rounding error in calculation of number of matrix files to created (100.mp4)
For some reason the calculation of the number of matrix files was rounded from 0.8... to 2 where the next bigger integer should be 1

fixes issue DEV-1513

### CODE REVIEW

**Comment by seakayone** [comment]
Before merging I should probably remove the huge .mp4 from the test_data folder as @jnussbaum pointed out to me. Keeping them for now for a convenience for our reviewers.

**Comment by BalduinLandolt** [comment]
in the PR title, "DEV" should be all-caps and in parentheses :)

**Review by BalduinLandolt — APPROVED** [review]
I don't really feel competent to review this one. But I couldn't see anything obvious, so as long as it works, I'm happy with it

**Review by irinaschubert — APPROVED** [review]
LGTM, jsut a minor remark: you added test data but no test, is that correct? Would it be possible to add a test for the 2 issues?

**Comment by seakayone** [comment]
> LGTM, jsut a minor remark: you added test data but no test, is that correct? Would it be possible to add a test for the 2 issues?

I will remove the "test_data/*.mp4" files before merging. I did not add any tests because:
1. There where no test present for it which I could easily extend.
2. This is a more elaborate workflow and unit testing bash scripts is very hard to do.

**Pull request merged**
