### PR TITLE
feature(ext search v1): add support for Geoname values (DSP-1493)

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves DSP-1493

### CODE REVIEW

**Review by benjamingeer — APPROVED** [review]

**Comment by tobiasschweizer** [comment]
@benjamingeer A little man in my head told me I should add a test which I did in https://github.com/dasch-swiss/dsp-api/pull/1840/commits/b0d1404e298aea8467482ddac8c95d0ab8f63eb5

**Comment by tobiasschweizer** [comment]
I think I messed up the PR's title: it should say "feat" and not "feature" ...

**Comment by subotic** [comment]
I think we will survive it ;-) let's see what release please does with it.

**Comment by tobiasschweizer** [comment]
I fear it'll ignore this PR in the changelog. However, @BalduinLandolt added some magic check to dsp-tools repo that would prevent this in the future.

**Pull request merged**
