### PR TITLE
fix: Replace rdf Property with owl ObjectProperty in knora-api (DEV-4220)

### PR DESCRIPTION
**Pull request by seakayone**
- **Replace RDF.Property with OWL.ObjectProperty in knora-api**
- **fix test**

### Task Description/Number

Issue Number: DEV-

### PR Type

- [ ] build/chore: maintenance tasks (no production code change)
- [ ] docs: documentation changes (no production code change)
- [ ] feat: represents new features
- [x] fix: represents bug fixes
- [ ] perf: performance improvements
- [ ] refactor: represents production code refactoring
- [ ] test: adding or refactoring tests (no production code change)
- [ ] deprecated: Deprecation warning (ideally referencing a migration guide)

### Basic requirements for bug fixes and features

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [ ] Yes

### CODE REVIEW

**Review by BalduinLandolt — APPROVED** [review]

**Review by Nora-Olivia-Ammann — COMMENTED** [review]
Will you change knora-base separately?
Other than that it looks good to me.

**Review by siers — APPROVED** [review]

**Review by mpro7 — APPROVED** [review]
Tests are still failing...

**Comment by seakayone** [comment]
> Tests are still failing...

Still? This is a flaky test that we have to fix at some point. Before merging main the tests succeeded. I rerun the tests.

**Comment by seakayone** [comment]
> Will you change knora-base separately? Other than that it looks good to me.

Good point, I will add it to this PR.

**Comment by seakayone** [comment]
Closing in favor of #3388 .

**Pull request closed without merging**
