### PR TITLE
chore: make targets for adding metadata (DSP-1289)

### PR DESCRIPTION
**Pull request by BalduinLandolt**
Resolves DSP-1289

### CODE REVIEW

**Comment by mpro7** [comment]
Thanks @BalduinLandolt, I add my 2 Rappens here instead MD channel.

I think `stack-down-delete-volumes` is obsolete, because `init-db-test` is covering it.

I would also not include into `make metadata` command others than these related to metadata, because most of the time at least `init-db-test` would be obsolete here too. IMO into `make metadata` I would include just `make stack-up` and all possible dataset to be loaded.

**Comment by BalduinLandolt** [comment]
@mpro7 thanks for your input!

Sadly, we can only ever have one metadata set at once, since I'm loading them into the same project, otherwise they would just overwrite one another.  
But yes, I'll change it right away.

**Review by mpro7 — APPROVED** [review]
This is it, thanks!

**Comment by BalduinLandolt** [comment]
@mpro7 I moved the metadata stuff to a separate `stack-up-with-metadata` target. @subotic did not want me to clutter `stack-up` even more.

**Review by mpro7 — APPROVED** [review]
Yes, that makes sense.

**Comment by subotic** [comment]
@BalduinLandolt I have changed the targets a bit. Could you please take a quick look and try it out?

**Pull request merged**
