### PR TITLE
DSP-1094 Upgrade Swagger version

### PR DESCRIPTION
**Pull request by SepidehAlassi**
resolves DSP-1094

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@subotic to fix the swagger problem, I had to upgrade its version. Since this version of swagger was using Akka HTTP 10.2.0, I had to also upgrade the AKK HTTP version. This solves the swagger issue. But as you can see some of the tests that expect rejection fail now. 
Can you please help me with solving this?

**Comment by subotic** [comment]
@SepidehAlassi  In general, the routes themselves don't know anything about how to return exceptions. This is implemented in the `KnoraExceptionHandler` and is wrapped around the routes in `ApplicationActor` on lines 415/417. I have moved the definition of this route directive into its own package and wrapped the routes of the failing tests with it.

It seems that they changed some things for `10.2.x` in this regard: https://doc.akka.io/docs/akka-http/current/migration-guide/migration-guide-10.2.x.html#providing-route-settings-exception-and-rejection-handling

**Comment by SepidehAlassi** [comment]
> @SepidehAlassi In general, the routes themselves don't know anything about how to return exceptions. This is implemented in the `KnoraExceptionHandler` and is wrapped around the routes in `ApplicationActor` on lines 415/417. I have moved the definition of this route directive into its own package and wrapped the routes of the failing tests with it.
> 
> It seems that they changed some things for `10.2.x` in this regard: https://doc.akka.io/docs/akka-http/current/migration-guide/migration-guide-10.2.x.html#providing-route-settings-exception-and-rejection-handling

yes, I read about this change but did not know how to modify our code to adapt to this change. Thanks for the fix.

**Review by benjamingeer — APPROVED** [review]

**Comment by benjamingeer** [comment]
Thanks to both of you for taking care of this.

**Comment by SepidehAlassi** [comment]
> Thanks to both of you for taking care of this.

Thanks for reviewing this.

**Pull request merged**
