### PR TITLE
chore: Use explicit label for actuated

### PR DESCRIPTION
**Pull request by alexellis**
Use explicit label for actuated

The "actuated" bare label has been deprecated. We've reached out several times to have this patched for Dasch Swiss, so I'm sending a PR to make it a bit easier.

The value for the vCPU and RAM matches the default. Feel free to amend as necessary in future PRs.

### Task Description/Number

Issue Number: DEV-

### PR Type

- [x] build/chore: maintenance tasks (no production code change)
- [ ] docs: documentation changes (no production code change)
- [ ] feat: represents new features
- [ ] fix: represents bug fixes
- [ ] perf: performance improvements
- [ ] refactor: represents production code refactoring
- [ ] test: adding or refactoring tests (no production code change)

### Basic requirements for bug fixes and features

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [ ] Yes

### Does this PR change client-test-data?

- [ ] Yes

### CODE REVIEW

**Comment by alexellis** [comment]
@subotic please could you take a look? I think this may be the remaining repository using the deprecated label format for actuated.

https://docs.actuated.dev/examples/custom-vm-size/

**Review by BalduinLandolt — APPROVED** [review]
Looks good to me. @subotic can be merged, right?

Thanks @alexellis for submitting the PR!

**Comment by alexellis** [comment]
Hi @BalduinLandolt yes it should be merged, this newer label is being used elsewhere already in the organisation.

For instance: https://github.com/dasch-swiss/dsp-meta/blob/9e4f2b9ba0ee5e17525e2d386a2fc34e7194456c/.github/workflows/main.yml#L14

Alex

**Comment by BalduinLandolt** [comment]
merged, thanks!

**Pull request merged**
