### PR TITLE
refactor: Migrate getGroup and getGroupMembers to tapir (DEV-1588)

### PR DESCRIPTION
**Pull request by mpro7**
### Task Description/Number

Issue Number: DEV-

### PR Type

- [ ] build/chore: maintenance tasks (no production code change)
- [ ] docs: documentation changes (no production code change)
- [ ] feat: represents new features
- [ ] fix: represents bug fixes
- [ ] perf: performance improvements
- [x] refactor: represents production code refactoring
- [ ] test: adding or refactoring tests (no production code change)

### Basic requirements for bug fixes and features

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [ ] Yes

### Does this PR change client-test-data?

- [ ] Yes

### CODE REVIEW

**Comment by seakayone** [comment]
LGTM, I was wondering that since you have exposed the `GroupResponder` methods
`groupGetRequest(iri: GroupIri): Task[GroupGetResponseADM]` and `groupMembersGetRequestADM(groupIri: IRI, requestingUser: User): Task[GroupMembersGetResponseADM` it should now be possible to remove the corresponding `*RequestADM` messages and instead of using the `MessageRelay` call the responder directly. 

In the past I have done this cleanup when migrating to tapir, are you planning to look into it?

**Review by seakayone — CHANGES_REQUESTED** [review]
I just noticed that the responses are not turned to the external format.

Please do this in the `GroupsRestService`.

**Comment by mpro7** [comment]
> LGTM, I was wondering that since you have exposed the `GroupResponder` methods `groupGetRequest(iri: GroupIri): Task[GroupGetResponseADM]` and `groupMembersGetRequestADM(groupIri: IRI, requestingUser: User): Task[GroupMembersGetResponseADM` it should now be possible to remove the corresponding `*RequestADM` messages and instead of using the `MessageRelay` call the responder directly.
> 
> In the past I have done this cleanup when migrating to tapir, are you planning to look into it?

I've done it that way, to avoid responder refactoring in this PR, because replacing it starts never-ending chain of changes.

> I just noticed that the responses are not turned to the external format.
> 
> Please do this in the `GroupsRestService`.

Sorry I don't get it. What is the external format you're referring too?

**Comment by seakayone** [comment]
> I've done it that way, to avoid responder refactoring in this PR, because replacing it starts never-ending chain of changes.
So you will get to it later?

> > I just noticed that the responses are not turned to the external format.
> > Please do this in the `GroupsRestService`.
> 
> Sorry I don't get it. What is the external format you're referring too?

You can use the `KnoraResponseRenderer`.

**Comment by mpro7** [comment]
> So you will get to it later?
> 
That was the plan.

> 
> You can use the `KnoraResponseRenderer`.
Thanks, I will try.

**Review by seakayone — APPROVED** [review]

**Review by BalduinLandolt — APPROVED** [review]

**Pull request merged**
