### PR TITLE
chore: bump scala to 2.13

### PR DESCRIPTION
**Pull request by subotic**
resolves DSP-1589

### CODE REVIEW

**Comment by benjamingeer** [comment]
Tests now failing because of:

```
Error:  OneForOneStrategy - You are using version 10.2.4 of Akka HTTP, but it appears you (perhaps indirectly)
also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version
10.2.4 of the [akka-http-spray-json, akka-http-testkit, akka-http-xml] artifacts to your project. See also:
https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
```

**Comment by subotic** [comment]
> Tests now failing because of:
> 
> ```
> Error:  OneForOneStrategy - You are using version 10.2.4 of Akka HTTP, but it appears you (perhaps indirectly)
> also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version
> 10.2.4 of the [akka-http-spray-json, akka-http-testkit, akka-http-xml] artifacts to your project. See also:
> https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
> ```

Thanks. Do you want to try and resolve this, or should I?

**Comment by benjamingeer** [comment]
I can try

**Comment by benjamingeer** [comment]
Fixed that, now it fails with:

```
java.lang.NoClassDefFoundError: org/bouncycastle/crypto/generators/SCrypt
	at org.springframework.security.crypto.scrypt.SCryptPasswordEncoder.decodeAndCheckMatches(SCryptPasswordEncoder.java:152)
	at org.springframework.security.crypto.scrypt.SCryptPasswordEncoder.matches(SCryptPasswordEncoder.java:134)
	at org.knora.webapi.messages.admin.responder.usersmessages.UserADM.$anonfun$passwordMatch$1(UsersMessagesADM.scala:533)
```

**Comment by benjamingeer** [comment]
OK fixed that I think

**Comment by benjamingeer** [comment]
@subotic OK everything compiles now and the tests pass.

**Comment by subotic** [comment]
> @subotic OK everything compiles now and the tests pass.

@benjamingeer great, thanks!

**Review by SepidehAlassi — APPROVED** [review]
LGTM

**Comment by benjamingeer** [comment]
@SepidehAlassi Thank you for reviewing this!

**Pull request merged**
