### PR TITLE
fix(sipi): remove support for audio/mp4 file format (DEV-1300)

### PR DESCRIPTION
**Pull request by mpro7**
Issue Number: DEV-1300

### Basic Requirements

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### PR Type

What kind of change does this PR introduce?

- [x] Bugfix: represents bug fixes
- [ ] Refactor: represents production code refactoring
- [ ] Feature: represents a new feature
- [ ] Documentation: documentation changes (no production code change)
- [ ] Chore: maintenance tasks (no production code change)
- [ ] Style: styles updates (no production code change)
- [ ] Test: all about tests: adding, refactoring tests (no production code change)
- [ ] Other... Please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Does this PR change client-test-data?

- [ ] Yes (don't forget to update the JS-LIB team about the change)
- [x] No

### CODE REVIEW

**Review by BalduinLandolt — APPROVED** [review]

**Comment by jnussbaum** [comment]
@mpro7 : Before you merge, we should perhaps fix something else: If I try to upload a DOCX file with dsp-tools, I get the following error:
```
Uploaded file ./Documents/RosettaTestproject.docx
ERROR while trying to create resource 'RosettaDOCX' (doc_002). Error message: KNORA-ERROR: status code=400
Message:{"knora-api:error":"dsp.errors.BadRequestException: File 9GOHhvFt4uN-Bs61Gi88Jij.docx has MIME type application/vnd.openxmlformats-officedocument.wordprocessingml.document, which is not supported for text files","@context":{"knora-api":"http://api.knora.org/ontology/knora-api/v2#"}}
```

Apparently, the MIME type is not recognized correctly.

**Comment by BalduinLandolt** [comment]
> @mpro7 : Before you merge, we should perhaps fix something else: If I try to upload a DOCX file with dsp-tools, I get the following error:
> 
> ```
> Uploaded file ./Documents/RosettaTestproject.docx
> ERROR while trying to create resource 'RosettaDOCX' (doc_002). Error message: KNORA-ERROR: status code=400
> Message:{"knora-api:error":"dsp.errors.BadRequestException: File 9GOHhvFt4uN-Bs61Gi88Jij.docx has MIME type application/vnd.openxmlformats-officedocument.wordprocessingml.document, which is not supported for text files","@context":{"knora-api":"http://api.knora.org/ontology/knora-api/v2#"}}
> ```
> 
> Apparently, the MIME type is not recognized correctly.

Why does it think that docx would be a "text file"? is that defined in the upload XML, in DSP-Tools, in SIPI or in DSP-API? Word files should be in the document category not in the text category, as far as I understand.

**Comment by mpro7** [comment]
> @mpro7 : Before you merge, we should perhaps fix something else: If I try to upload a DOCX file with dsp-tools, I get the following error:
> 
> ```
> Uploaded file ./Documents/RosettaTestproject.docx
> ERROR while trying to create resource 'RosettaDOCX' (doc_002). Error message: KNORA-ERROR: status code=400
> Message:{"knora-api:error":"dsp.errors.BadRequestException: File 9GOHhvFt4uN-Bs61Gi88Jij.docx has MIME type application/vnd.openxmlformats-officedocument.wordprocessingml.document, which is not supported for text files","@context":{"knora-api":"http://api.knora.org/ontology/knora-api/v2#"}}
> ```
> 
> Apparently, the MIME type is not recognized correctly.

It seems not to be related to

**Comment by jnussbaum** [comment]
@BalduinLandolt: You're right. I made it wrong in my XML file. Sorry for having you disturbed :-)

**Comment by BalduinLandolt** [comment]
@jnussbaum no worries! I'd rather have it that way, than needing to fix stuff in the API (or even worse, in SIPI)... :-)

**Pull request merged**
