### PR TITLE
chore: check that the expected Fuseki version is present (DEV-331)

### PR DESCRIPTION
**Pull request by irinaschubert**
Resolves DEV-331

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

## What is the current behavior?

Issue Number: DEV-331

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by BalduinLandolt — APPROVED** [review]
LGTM.  
In terms of code style: I think such long comments should not be on the same line as the code, but on the line before. But that's cosmetics

**Comment by BalduinLandolt** [comment]
> > LGTM. In terms of code style: I think such long comments should not be on the same line as the code, but on the line before. But that's cosmetics
> 
> OK, I understand. I thought if it is on the same line, it is more obvious that it should be read. If it is above, one could easily not see it and forget to udpate the versions in the other places. What is your opinion on that?

Also makes sense. And if it has a functional purpose, I'm happy to live with a bit of ugly long lines :)

**Review by subotic — APPROVED** [review]

**Review by mpro7 — APPROVED** [review]
I would rather place comments in new line instead of making lines so long.

**Comment by irinaschubert** [comment]
> I would rather place comments in new line instead of making lines so long.

I leave it on the same line. I'm afraid that we could forget to update the version in ops-deploy if we put the comment above or below. Hope that's OK for you, @mpro7 . We can still change it in the future should it bother us too much.

**Comment by mpro7** [comment]
> > I would rather place comments in new line instead of making lines so long.
> 
> I leave it on the same line. I'm afraid that we could forget to update the version in ops-deploy if we put the comment above or below. Hope that's OK for you, @mpro7 . We can still change it in the future should it bother us too much.

IMO it works the other way around. Longer lines are usually less readable and easy to omit the info. That's just general remark and one of good practices to break the lines if too long, but yeah... whatever ;)

**Pull request merged**
