### PR TITLE
feat(gh-ci): Release please and update gh actions (DSP-1168)

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves DSP-1168

- Add a changelog file. This will be updated by "release please action" after merging this PR
- Add version.txt file. This will be updated by "release please action".
- Add "release please action" and remove "release drafter"
- Update github actions workflow: Separate step to deploy documentation on release --> DSP-917

### CODE REVIEW

**Review by mpro7 — APPROVED** [review]
Looks good for me.

**Review by benjamingeer — APPROVED** [review]
Thank you!

**Comment by benjamingeer** [comment]
Do I understand correctly that breaking changes now have to be indicated in two different ways:

- by an `!` in a commit message
- by a `breaking` tag on the PR

But only the `-` affects the release version number? If that's correct, what is the tag on the PR used for? Do we need it?

**Comment by kilchenmann** [comment]
> Do I understand correctly that breaking changes now have to be indicated in two different ways:
> 
> * by an `!` in a commit message
> * by a `breaking` tag on the PR
> 
> But only the `!` affects the release version number? If that's correct, what is the tag on the PR used for? Do we need it?

What do you mean by "tag"? Do you mean the label? The label is now optional (https://docs.dasch.swiss/developers/dsp/contribution/#add-a-label-optional) but it could help to see corresponding code changes directly in a PR. And you can set more than one label but only one type in the title.

**Comment by benjamingeer** [comment]
> What do you mean by "tag"? Do you mean the label? The label is now optional

Yes, OK. Can you please make some sort of announcement to make sure that everyone knows this? I had got used to the label being the thing that's machine-readable and is needed for releases.

**Comment by mpro7** [comment]
@benjamingeer we announce it on the R&D channel once we are ready with all changes.

**Pull request merged**
