### PR TITLE
DSP-1106 Update Permission

### PR DESCRIPTION
**Pull request by SepidehAlassi**
resolves DSP-1106
Add the following routes for both default object access permission (doap) and administrative permission (ap)
- [x] `Put admin/permissions/<permissionIri>/group` update a permission's group (doap or ap) 
- [x] `Put admin/permissions/<permissionIri>/hasPermissions` update a permission's `hasPermissions` (doap or ap) 
- [x] `Put admin/permissions/<permissionIri>/resourceClass` update a doap permission's resource class
- [x] `Put admin/permissions/<permissionIri>/property` update a doap permission's property
For `Put` requests, the new values must be given in the request body

- [x] add tests
- [x] add test data
- [x] add documentation

### CODE REVIEW

**Review by benjamingeer — CHANGES_REQUESTED** [review]
This isn't something that was changed in this PR, but I just noticed that in `PermissionsResponderADM.userAdministrativePermissionsGetADM`, there's something that looks like a bug:

```scala
    val permissionsPerProject: Iterable[Future[(IRI, Set[PermissionADM])]] = for {
      (projectIri, groups) <- groupsPerProject

      /* Explicitly add 'KnownUser' group */
      extendedUserGroups = OntologyConstants.KnoraAdmin.KnownUser ++ groups

      result = calculatePermission(projectIri, groups)

    } yield result
```

The variable `extendedUserGroups` is defined but its value is never used.

**Comment by SepidehAlassi** [comment]
> This isn't something that was changed in this PR, but I just noticed that in `PermissionsResponderADM.userAdministrativePermissionsGetADM`, there's something that looks like a bug:
> 
> ```scala
>     val permissionsPerProject: Iterable[Future[(IRI, Set[PermissionADM])]] = for {
>       (projectIri, groups) <- groupsPerProject
> 
>       /* Explicitly add 'KnownUser' group */
>       extendedUserGroups = OntologyConstants.KnoraAdmin.KnownUser ++ groups
> 
>       result = calculatePermission(projectIri, groups)
> 
>     } yield result
> ```
> 
> The variable `extendedUserGroups` is defined but its value is never used.

Thanks for pointing this out, I believe since `KnownUser` is most of the time already in the groups of the project,  this bug has not shown itself. 
However, one should make sure that administrative permissions for `KnownUser` is also returned by `calculatePermission` method. Therefore, `extendedUserGroups` including `KnownUser` should be passed as its parameter.

**Review by benjamingeer — APPROVED** [review]
OK thanks very much!

**Comment by SepidehAlassi** [comment]
@benjamingeer Thanks for reviewing this!

**Pull request merged**
