### PR TITLE
feat(Gravsearch): Enable ORDER BY external link (DEV-2704)

### PR DESCRIPTION
**Pull request by mpro7**
### Task Description/Number

Issue Number: DEV-2704

### PR Type

- [ ] fix: represents bug fixes
- [ ] refactor: represents production code refactoring
- [x] feat: represents a new feature
- [ ] docs: documentation changes (no production code change)
- [ ] chore: maintenance tasks (no production code change)
- [ ] test: all about tests: adding, refactoring tests (no production code change)
- [ ] other... Please describe:

### Basic Requirements for bug fixes and features

- [x] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [ ] Yes

### Does this PR change client-test-data?

- [ ] Yes

### CODE REVIEW

**Review by BalduinLandolt — APPROVED** [review]
LGTM

**Comment by seakayone** [comment]
I'm uncertain about how to interpret this PR. The underlying issue is related to an error in a specific query. You've added tests for two similar queries, but it appears that no changes were made to the production code. This raises some questions for me:

1. Does the error still exists in our stage environment where @mdelez has reported the problem? If it does, how does this PR address that issue? If not, do you know what resolved the original problem?
2. Your tests currently only assert the HTTP status code. Are we confident that the ORDER BY clause is functioning correctly? Would it be a good idea to include assertions to ensure that the returned results are ordered as expected? I would even suggest having a test that checks if `ORDER BY DESC(?prop0)` returns the reverse order.

**Comment by mpro7** [comment]
> I'm uncertain about how to interpret this PR. The underlying issue is related to an error in a specific query. You've added tests for two similar queries, but it appears that no changes were made to the production code. This raises some questions for me:
> 
> 1. Does the error still exists in our stage environment where @mdelez has reported the problem? If it does, how does this PR address that issue? If not, do you know what resolved the original problem?
> 2. Your tests currently only assert the HTTP status code. Are we confident that the ORDER BY clause is functioning correctly? Would it be a good idea to include assertions to ensure that the returned results are ordered as expected? I would even suggest having a test that checks if `ORDER BY DESC(?prop0)` returns the reverse order.
> 
> Edit: I initially misunderstood the change to the `AbstractPreQueryGenerator` as a simple property ordering adjustment. However, upon closer inspection, I see that you've added two mappings: `Xsd.Uri` and `KnoraApiV2Complex.UriValue`. This addresses my initial question nr. 1.
> 
> Upon further reflection, and this may be a question for the issue creator, @mdelez: If I understand correctly, the 'uri' property being used for sorting contains the value of the actual URI. Is this really suitable for creating a meaningful order?

This small PR just enables something in already working sorting feature. I find the idea of checking the order in this case simply as the over-testing.

**Comment by mdelez** [comment]
@seakayone Whether or not the ordering of a URI value is meaningful or not, I don't see a reason why we wouldn't allow a user to do it. It may be meaningful for the user in some way if they have very specific URIs that they know can be sorted alphabetically to help them find their data faster.

**Review by seakayone — APPROVED** [review]

**Comment by mpro7** [comment]
I found the `searchextended` route order being already checked in one of the `SearchResponderV2Spec` tests.

**Pull request merged**
