### PR TITLE
refactor(audio): remove not required properties

### PR DESCRIPTION
**Pull request by subotic**
Resolves DEV-

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by kilchenmann — APPROVED** [review]
seems to work 👍

**Review by mpro7 — COMMENTED** [review]
I don't understand the changes in TTL files, which I see not directly related to removal duration information from audio.

**Review by irinaschubert — APPROVED** [review]

**Comment by subotic** [comment]
> I don't understand the changes in TTL files, which I see not directly related to removal duration information from audio.

As the data inside the triplestore has changed (duration property removed), the responses from the triplestore have also changed. The order in which the triplestore returns is data is arbitrary. That's why the changes inside the generated files are mixed up.

**Review by BalduinLandolt — APPROVED** [review]
Looks good

**Pull request merged**
