### PR TITLE
feat(listsEndpoint) Insert list item in specific position (DSP-1227)

### PR DESCRIPTION
**Pull request by SepidehAlassi**
resolves DSP-1227

### CODE REVIEW

**Review by benjamingeer — APPROVED** [review]
Looks good to me, thanks very much!

**Review by subotic — APPROVED** [review]
cool, thanks :-)

**Comment by subotic** [comment]
@SepidehAlassi could you please wait with merging for after the release has happened? I had to change the changelog by hand and merging this PR would overwrite my edits. Thanks.

**Comment by SepidehAlassi** [comment]
> @SepidehAlassi could you please wait with merging for after the release has happened? I had to change the changelog by hand and merging this PR would overwrite my edits. Thanks.

Sure!

**Comment by SepidehAlassi** [comment]
@benjamingeer & @subotic thank you very much for reviewing this!

**Comment by subotic** [comment]
@SepidehAlassi release ist through. You can merge whenever you like. Thanks for waiting.

**Pull request merged**
