### PR TITLE
chore: Spring cleaning the code base

### PR DESCRIPTION
**Pull request by BalduinLandolt**
### Task Description/Number

This PR gets rid of a bunch of old TODOs, commented out code, nonsensical logs, unused files, etc.  
(Note: `response.toString()` does not give any useful information that might be worth printing, so I removed a number of those too.)

### PR Type

- [x] build/chore: maintenance tasks (no production code change)
- [ ] docs: documentation changes (no production code change)
- [ ] feat: represents new features
- [ ] fix: represents bug fixes
- [ ] perf: performance improvements
- [ ] refactor: represents production code refactoring
- [ ] test: adding or refactoring tests (no production code change)

### Basic requirements for bug fixes and features

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [ ] Yes

### Does this PR change client-test-data?

- [ ] Yes

### CODE REVIEW

**Review by seakayone — APPROVED** [review]

**Comment by seakayone** [comment]
**praise**: This spring clean-up pull request is like having Marie Kondo organize your codebase – it sparks joy and leaves everything feeling refreshingly streamlined and clutter-free!

**Comment by BalduinLandolt** [comment]
> **praise**: This spring clean-up pull request is like having Marie Kondo organize your codebase – it sparks joy and leaves everything feeling refreshingly streamlined and clutter-free!

Happy to spark joy! :)

Sadly, there is still plenty of stuff to clean up, still... Marie Kondo would not accept this, I think. But I'm nerd enough that I had to stop when I had reached 42 files changed. 😄

**Review by siers — APPROVED** [review]
**praise:** Great! :)

**Review by mpro7 — APPROVED** [review]
Thank you Mr. Proper  ;)

**Pull request merged**
