### PR TITLE
feat(knora-ontologies): Add project metadata system ontology

### LINKED ISSUE #1454: Implement a system ontology for Knora projects metadata
After discussing with @lrosenth and @subotic, and following issues #525 and #566, the knora projects metadata ontology should be implemented as a `system ontology`.

- @subotic and @lrosenth will provide the draft for this ontology 
- I will proceed on this base to add the classes and properties listed [here](https://discuss.dasch.swiss/t/first-draft-for-projects-metadata/97/4) 
- I will map them with at least a standard ontology ([DCAT-AP](https://joinup.ec.europa.eu/release/dcat-ap/121) being the first choice).

### PR DESCRIPTION
**Pull request by subotic**
resolves #1454

### CODE REVIEW

**Comment by subotic** [comment]
@mrivoal we can use this branch to work on the ontology. I've created the file `knora-ontologies/knora-project-metadata.ttl`

**Comment by mrivoal** [comment]
Thank you! Will do :)

**Comment by mrivoal** [comment]
I committed a first draft of the ontology. I would have liked to test it, but as it is a system ontology, I don't think I will be able to do this.

I would appreciate if the ontology itself could be reviewed and validated (or not!) as it is. I have changed a little be the original specification (mainly move metadata from `Project` to `Database`). The current draft implements this schema:

metadata-DaSCH-data-model_V2

**Comment by mrivoal** [comment]
In the next steps I would like to : 

1. map it with standard ontologies
2. suggest and implement controlled vocabularies the way we spoke above.
3. test it with real project metadata

Afterwards, the next steps I can figure out are these : 

4. have the metadata displayed by knora-api. Maybe at : https://knora.unil.ch/admin/projects/shortcode/0114 ?
5. have the metadata displayed in knora-app:
  - maybe at https://knora.unil.ch/project/0114/info ?
  - metadata should also be made downloadable in standard formats. See for example the format/ontologies displayed by Dataverse : https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/P5H5ET

Capture d’écran 2019-10-25 à 10 46 50

What do you think? Am I missing something?

**Comment by mrivoal** [comment]
@subotic How should we proceed on this issue? 

Any feedback on the data model (which implement with minor changes https://discuss.dasch.swiss/t/first-draft-for-projects-metadata/97/2) ? I would like to be sure that there is a consensus on this before mapping the suggested ontology with standard ones.

**Comment by subotic** [comment]
@mrivoal Looks good. We have to think about how we will connect an instance of `knora-admin:knoraProject` to `knora-project-metadata:Project`. Maybe we should rename `knora-project-metadata:Project` to `knora-project-metadata:ExtendedProjectInformation` via a property like `knora-admin:hasExtendedProjectInformation`.

Also, could you please open a design document in https://github.com/dasch-swiss/knora-proposals  where we can write down the results of the different discussions on this topic.

**Comment by mrivoal** [comment]
Thanks!

> Also, could you please open a design document in https://github.com/dasch-swiss/knora-proposals where we can write down the results of the different discussions on this topic.

Yes, will do.

**Comment by subotic** [comment]
deprecated through implementation in the metadata-service.

**Pull request closed without merging**
