### PR TITLE
fix(OntologyResponderV2): Fix check when updating ontology label and comment (DSP-1390)

### PR DESCRIPTION
**Pull request by benjamingeer**
resolves DSP-1390
resolves DSP-1397

### CODE REVIEW

**Comment by mdelez** [comment]
Looks good to me! Could you also add some logic to allow an empty string for a comment? I don't believe comments are required and currently there is no way to remove a comment once one is provided.

**Comment by benjamingeer** [comment]
@mdelez Thanks!

> Could you also add some logic to allow an empty string for a comment?

We don't allow empty strings in the triplestore, so I guess we have two options:

1. Change the semantics of that route so that if you don't provide a comment, the existing comment is removed.
2. Add a separate route for deleting the comment.

Please open a separate YouTrack issue for this indicating which you prefer.

**Comment by mdelez** [comment]
separate Youtrack issue has been made https://dasch.myjetbrains.com/youtrack/issue/DSP-1397

**Review by SepidehAlassi — APPROVED** [review]
This is great, thank you!

**Pull request merged**
