### PR TITLE
feat(admin): Represent a string with a required language tag

### LINKED ISSUE #1419: Creating a label in a list without a language tag is not allowed anymore

### PR DESCRIPTION
**Pull request by benjamingeer**
- [x] Add a case class representing a string with a required language tag.
- [x] Use it for the `description` of a project.
- [ ] Use it in lists.

@subotic Will this be OK, and if so, would you like to finish this PR?

Resolves #1419.

### CODE REVIEW

**Comment by subotic** [comment]
@benjamingeer great, thanks. I will finish it. Will have to think of a way to make it backward compatible. I'm not keen on writing an upgrade script for admin data, just to add a language tag.

**Comment by subotic** [comment]
@SepidehAlassi This is an open PR, which would need your attention ;-) It is connected to #1419 which you commented on last week or so.

**Comment by subotic** [comment]
@SepidehAlassi is this something that you maybe already did as part of some other PR?

**Comment by SepidehAlassi** [comment]
> @SepidehAlassi is this something that you maybe already did as part of some other PR?

No, I have not done this. It would need writing a migration task to add language tag to labels and comments of the nodes in the existing lists. I can do it though, please make a user story for it.

**Pull request closed without merging**
