### PR TITLE
chore(formatting): Add trailing commas

### PR DESCRIPTION
**Pull request by BalduinLandolt**
### Task Description/Number

Issue Number: DEV-

### PR Type

- [x] build/chore: maintenance tasks (no production code change)
- [ ] docs: documentation changes (no production code change)
- [ ] feat: represents new features
- [ ] fix: represents bug fixes
- [ ] perf: performance improvements
- [ ] refactor: represents production code refactoring
- [ ] test: adding or refactoring tests (no production code change)

### Basic requirements for bug fixes and features

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [ ] Yes

### Does this PR change client-test-data?

- [ ] Yes

### CODE REVIEW

**Review by siers — APPROVED** [review]
😍

**Review by seakayone — APPROVED** [review]

**Comment by seakayone** [comment]
*praise*: This is something I wish we had for a long time already

FYI: I have added this to dsp-ingest: https://github.com/dasch-swiss/dsp-ingest/pull/180

**Review by mpro7 — APPROVED** [review]
This kind of formatting taks is good to announce and start when nothing is in progress due to conflicts hell, hopefully it will go smooth.

**Comment by BalduinLandolt** [comment]
> This kind of formatting taks is good to announce and start when nothing is in progress due to conflicts hell, hopefully it will go smooth.

You're right. It's something I remembered spontaneously, but I should have announced it. However, it's an easy one to resolve any conflicts: You can just accept any other change, and then do `fmt`

**Pull request merged**
